<?php

namespace App\Utilities;

use App\Entities\ServiceAgreement;
use Exception;
use Illuminate\Support\Collection;

class ServiceAgreementCollection extends Collection
{
    private static $allowedType = ServiceAgreement::class;

    public function add($item)
    {
        $this->isAllowed($item);

        return parent::add($item); // TODO: Change the autogenerated stub
    }

    public function push(...$values)
    {
        foreach ($values as $value) {
            $this->isAllowed($value);
        }

        return parent::push($values); // TODO: Change the autogenerated stub
    }

    private function isAllowed($item)
    {
        if (!$item instanceof self::$allowedType) {
            throw new Exception(sprintf("Only types %s are allowed.", self::$allowedType));
        }
    }
}